### ISSUE TITLE
[BUG] No error thrown for invalid condition

### ISSUE THREAD

**Issue by dipack95** [dynamoose/dynamoose#1323]
### Summary:

Dynamoose does not throw/log an error when we create an invalid `Dynamoose#Condition`, using the DynamoDB condition syntax. This causes silent logic bugs!

#### Schema
```javascript
const definition = new dynamoose.Schema(
    {
        id: {
            type: String,
            required: true,
        },
        value: {
            type: String,
            required: true,
        },
        randomNumber: {
            type: Number,
            required: true,
        },
    },
    {
        /**
         * Let Dynamoose manage the `createdAt` and `updatedAt` timestamps,
         * Unix epoch in seconds (not milliseconds)
         */
        timestamps: true,
    },
);

```

#### Model
```javascript
const tableName = 'dipack_dynamoose_bug_repro';
const Model = dynamoose.model(tableName, definition, { create: true });

```

#### General
```javascript
// ========== ALL CODE HERE INCLUDING SCHEMA AND MODEL =============

const dynamoose = require('dynamoose');

const ddb = new dynamoose.aws.sdk.DynamoDB({
    region: 'eu-west-1',
    version: 'latest',
});

dynamoose.aws.ddb.set(ddb);

const tableName = 'dipack_dynamoose_bug_repro';

const definition = new dynamoose.Schema(
    {
        id: {
            type: String,
            required: true,
        },
        value: {
            type: String,
            required: true,
        },
        randomNumber: {
            type: Number,
            required: true,
        },
    },
    {
        /**
         * Let Dynamoose manage the `createdAt` and `updatedAt` timestamps,
         * Unix epoch in seconds (not milliseconds)
         */
        timestamps: true,
    },
);

const DELETION_THRESHOLD_MS = (1000 * 60);
const now = Date.now();

const buggyQuery = new dynamoose.Condition({
    FilterExpression: '#createdAtCol <= :createdAtValue OR #updatedAtCol <= :updatedAtValue',
    ExpressionAttributeValues: {
        ':createdAtValue': {
            N: now - DELETION_THRESHOLD_MS,
        },
        ':updatedAtValue': {
            N: now - DELETION_THRESHOLD_MS,
        },
    },
    ExpressionAttributeNames: {
        '#createdAtCol': 'createdAt',
        '#updatedAtCol': 'updatedAt',
    },
});

const workingQueryDyn = new dynamoose.Condition().where('createdAt').le(now - DELETION_THRESHOLD_MS).or().where('updatedAt').le(now - DELETION_THRESHOLD_MS);

(async () => {
    const Model = dynamoose.model(tableName, definition, { create: true });
    const existingRows = await Model.scan().exec();
    console.log(`Found ${existingRows.length} rows.`);
    const newRows = await Promise.all(
        new Array(5).fill(0).map(async (_, idx) => {
            const id = Math.floor(Math.random() * 10 ** 10);
            const row = await Model.create({
                id: String(id),
                value: `${id}-${idx}`,
                randomNumber: Math.random(),
            });
            return row;
        })
    ).catch(err => console.error('Error while creating new rows', err));
    console.log(`Created ${newRows.length} new rows.`);
    const filteredRows = await Model.scan(buggyQuery).exec();
    console.log(`Filtered ${filteredRows.length} rows using DynamoDB condition API`);
    const allRows = await Model.scan().exec();
    if (allRows.every(row => filteredRows.find(fRow => fRow.id === row.id) !== undefined)) {
        console.warn('No rows were filtered!');
    }
    const filteredRowsDyn = await Model.scan(workingQueryDyn).exec();
    console.log(`Filtered ${filteredRowsDyn.length} rows using Dynamoose condition API`);
    if (allRows.every(row => filteredRowsDyn.find(fRow => fRow.id === row.id) !== undefined)) {
        console.warn('No rows were filtered, using the Dynamoose API too!');
    }
    console.log('DynamoDB API condition object', buggyQuery.requestObject());
    console.log('Dynamoose API condition object', workingQueryDyn.requestObject());
})();

```

### Current output and behavior (including stack trace):

The DynamoDB based Condition is currently shown as an empty object.

```bash
Found 105 rows.
Created 5 new rows.
Filtered 110 rows using DynamoDB condition API
Filtered 100 rows using Dynamoose condition API
DynamoDB API condition object {}
Dynamoose API condition object {
  ConditionExpression: '#a0 <= :v0 OR #a1 <= :v1',
  ExpressionAttributeNames: { '#a0': 'createdAt', '#a1': 'updatedAt' },
  ExpressionAttributeValues: { ':v0': { N: '1640063029486' }, ':v1': { N: '1640063029486' } }
}

```

### Expected output and behavior:

Expect the condition objects built using the DynamoDB syntax, and the Dynamoose API to be the same. If the condition generated is invalid, then we should throw an error.

### Environment:

Operating System: MacOS
Operating System Version: 12.1 Monterey
Node.js version (`node -v`): 14.17.3
NPM version: (`npm -v`): 6.14.13
Dynamoose version: 2.8.3

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [ ] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [x] I have tested the code provided and am confident it doesn't work as intended
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@dipack95

> `buggyQuery.requestObject()`

This is expected to return `{}`. So that is not a bug. Additionally, this behavior is not documented. Please see [this page](https://dynamoosejs.com/other/FAQ#can-i-use-an-undocumented-property-class-method-or-function-in-dynamoose) for more information. I do understand that this was used as an example tho to demonstrate your point, however technically it is irrelevant since the correct command is `requestObject({"conditionString": "FilterExpression", "conditionStringType": "array"})`: https://github.com/dynamoose/dynamoose/blob/ed6f3802f7281dbd85987ac58b0661c2fc686417/lib/DocumentRetriever.ts#L149

So ignoring this part of the bug.

> `await Model.scan(buggyQuery).exec()`

This bug should be fixed in #1324. If you could please test & review that PR before I merge that would be awesome!! You can get instructions for [how to install a Dynamoose branch here](https://dynamoosejs.com/getting_started/Install#branch).

Please report back if that works for you.

**Comment by dipack95** [comment]
@fishcharlie Thanks for responding so quickly!

> This is expected to return {}. So that is not a bug. 

I understand that `requestObject()` method might be undocumented, and therefore unreliable, but the reason I use that in the code example is to highlight how we have Dynamoose correctly composing the right request when we use the Dynamoose API to create a scan condition, versus what happens when we give it a (I'm assuming) incorrect DynamoDB condition object, which causes a bug where no condition is applied to the `Scan` itself. In those case, I believe an error should be thrown if we have specified an input object condition, but get an empty object in return.

Also, thank you for the PR #1324! I'm going to test it out right now, and get back to you :)

**Comment by dipack95** [comment]
@fishcharlie I've just tested out PR #1324, and it looks like the request object is now being composed correctly! The filtering still does not take place as expected though..

```bash
Found 135 rows.
Created 5 new rows.
Filtered 140 rows using DynamoDB condition API
Filtered 130 rows using Dynamoose condition API
DynamoDB API condition object {
  ConditionExpression: '#createdAtCol <= :createdAtValue OR #updatedAtCol <= :updatedAtValue',
  ExpressionAttributeValues: {
    ':createdAtValue': { N: 1640205436106 },
    ':updatedAtValue': { N: 1640205436106 }
  },
  ExpressionAttributeNames: { '#createdAtCol': 'createdAt', '#updatedAtCol': 'updatedAt' }
}
Dynamoose API condition object {
  ConditionExpression: '#a0 <= :v0 OR #a1 <= :v1',
  ExpressionAttributeNames: { '#a0': 'createdAt', '#a1': 'updatedAt' },
  ExpressionAttributeValues: { ':v0': { N: '1640205436106' }, ':v1': { N: '1640205436106' } }
}
```

This is still a step in the right direction -- thanks for being so responsive!

**Comment by fishcharlie** [comment]
@dipack95 How is the filtering not correct? You haven't provided enough information for me to debug that further.

**Comment by dipack95** [comment]
@fishcharlie Using the PR that you've created, I was able to see that one thing I was doing incorrectly was using `FilterExpression` over `ConditionExpression`. Once I fixed that, I ran the script again, and if you see the output in the earlier comment (https://github.com/dynamoose/dynamoose/issues/1323#issuecomment-999867215), we see that we "filter" 140 rows using the DynamoDB condition API, and 130 rows (the right amount) using the Dynamoose condition API. 

That is what I mean by the filtering being incorrect.

```javascript
const dynamoose = require('dynamoose');

const ddb = new dynamoose.aws.sdk.DynamoDB({
    region: 'eu-west-1',
    version: 'latest',
});

dynamoose.aws.ddb.set(ddb);

const tableName = 'dipack_dynamoose_bug_repro';

const definition = new dynamoose.Schema(
    {
        id: {
            type: String,
            required: true,
        },
        value: {
            type: String,
            required: true,
        },
        randomNumber: {
            type: Number,
            required: true,
        },
    },
    {
        /**
         * Let Dynamoose manage the `createdAt` and `updatedAt` timestamps,
         * Unix epoch in seconds (not milliseconds)
         */
        timestamps: true,
    },
);

const DELETION_THRESHOLD_MS = (1000 * 60);
const now = Date.now();

const buggyQuery = new dynamoose.Condition({
    //FilterExpression: '#createdAtCol <= :createdAtValue OR #updatedAtCol <= :updatedAtValue',
    ConditionExpression: '#createdAtCol <= :createdAtValue OR #updatedAtCol <= :updatedAtValue',
    ExpressionAttributeValues: {
        ':createdAtValue': {
            N: now - DELETION_THRESHOLD_MS
        },
        ':updatedAtValue': {
            N: now - DELETION_THRESHOLD_MS,
        },
    },
    ExpressionAttributeNames: {
        '#createdAtCol': 'createdAt',
        '#updatedAtCol': 'updatedAt',
    },
});

const workingQueryDyn = new dynamoose.Condition().where('createdAt').le(now - DELETION_THRESHOLD_MS).or().where('updatedAt').le(now - DELETION_THRESHOLD_MS);

(async () => {
    const Model = dynamoose.model(tableName, definition, { create: true });
    const existingRows = await Model.scan().exec();
    console.log(`Found ${existingRows.length} rows.`);
    const newRows = await Promise.all(
        new Array(5).fill(0).map(async (_, idx) => {
            const id = Math.floor(Math.random() * 10 ** 10);
            const row = await Model.create({
                id: String(id),
                value: `${id}-${idx}`,
                randomNumber: Math.random(),
            });
            return row;
        })
    ).catch(err => console.error('Error while creating new rows', err));
    console.log(`Created ${newRows.length} new rows.`);
    const filteredRows = await Model.scan(buggyQuery).exec();
    console.log(`Filtered ${filteredRows.length} rows using DynamoDB condition API`);
    const allRows = await Model.scan().exec();
    if (allRows.every(row => filteredRows.find(fRow => fRow.id === row.id) !== undefined)) {
        console.warn('No rows were filtered!');
    }
    const filteredRowsDyn = await Model.scan(workingQueryDyn).exec();
    console.log(`Filtered ${filteredRowsDyn.length} rows using Dynamoose condition API`);
    if (allRows.every(row => filteredRowsDyn.find(fRow => fRow.id === row.id) !== undefined)) {
        console.warn('No rows were filtered, using the Dynamoose API too!');
    }
    console.log('DynamoDB API condition object', buggyQuery.requestObject());
    console.log('Dynamoose API condition object', workingQueryDyn.requestObject());
})();

```

**Comment by fishcharlie** [comment]
@dipack95 Please do me a favor and dig into this a bit further yourself. I have limited resources and insight into your code and items in your table.

Maybe try running "dynamoose.logger.providers.set([console]);" to see what that outputs.

And please work on trying to create an MCVE.

As far as I can tell everything is working fine. I need more context here about what specifically isn't working as opposed to just a bunch of code (most of which isn't relevant to this issue).

**Comment by dipack95** [comment]
@fishcharlie Will do, thanks for your help so far!

**Comment by fishcharlie** [comment]
@dipack95 No problem! Keep me posted. Really want to help get this resolved for you but just need more specific information so it's quick and easy for me to debug and fix (if necessary).

**Comment by fishcharlie** [comment]
@dipack95 I think I found what you are doing wrong. `FilterExpression` is correct, **not** `ConditionExpression`. See https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Scan.html for more information.

I'm also curious why you are using a RAW condition object at all. Is there a reason you don't just stick with the Dynamoose API? I know we advertise that both work, so we should fix whatever bug exists. But just curious why you are choosing to use the raw object over the Dynamoose condition API.

**Comment by dipack95** [comment]
@fishcharlie I finally figured out the issues!

> FilterExpression is correct, not ConditionExpression

This was a useful tip -- I switched over to use `ConditionExpression` in https://github.com/dynamoose/dynamoose/issues/1323#issuecomment-999870129 because the request object printed using the Dynamoose condition API listed `ConditionExpression`, so I thought I was using the DynamoDB API incorrectly. That maybe a bug?

The second issue I found that made me think I had to use `ConditionExpression` over `FilterExpression`, is when we pass in a DynamoDB object based condition, like:

```javascript
const buggyQuery = new dynamoose.Condition({
    FilterExpression: '#createdAtCol <= :createdAtValue OR #updatedAtCol <= :updatedAtValue',
    ExpressionAttributeValues: {
        ':createdAtValue': {
            N: String(now - DELETION_THRESHOLD_MS)
        },
        ':updatedAtValue': {
            N: String(now - DELETION_THRESHOLD_MS)
        },
    },
    ExpressionAttributeNames: {
        '#createdAtCol': 'createdAt',
        '#updatedAtCol': 'updatedAt',
    },
});
```

Dynamoose throws an error [here](https://github.com/dynamoose/dynamoose/blob/main/lib/utils/dynamoose/convertConditionArrayRequestObjectToString.ts#L2), as it's expecting `FilterExpression` to be an array, and that really confused the hell out of me -- admittedly, if I'd read the message correctly earlier, we wouldn't have had to have this back and forth -- I fixed the query by modifying the `buggyQuery` as follows, and found that filtering now works the exact same way using both APIs!

```javascript
const buggyQuery = new dynamoose.Condition({
    FilterExpression: ['#createdAtCol <= :createdAtValue OR #updatedAtCol <= :updatedAtValue'],
    ExpressionAttributeValues: {
        ':createdAtValue': {
            N: String(now - DELETION_THRESHOLD_MS)
        },
        ':updatedAtValue': {
            N: String(now - DELETION_THRESHOLD_MS)
        },
    },
    ExpressionAttributeNames: {
        '#createdAtCol': 'createdAt',
        '#updatedAtCol': 'updatedAt',
    },
});
```

I believe that to be the second bug, as the DynamoDB NodeJS API does support passing in plain strings as `FilterExpression` -- [link](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.NodeJs.04.html#GettingStarted.NodeJs.04.Scan).

> I'm also curious why you are using a RAW condition object at all. Is there a reason you don't just stick with the Dynamoose API?

I had decided to use the DynamoDB condition object over the Dynamoose Condition API as I'd been running into a few issues when querying the timestamp columns like `createdAt`, `updatedAt`, which were managed by Dynamoose (using the `timestamps: true` option on model instantiation). I cannot remember the exact issues I was facing then, unfortunately.

**Comment by fishcharlie** [comment]
@dipack95 

> This was a useful tip -- I switched over to use ConditionExpression in #1323 (comment) because the request object printed using the Dynamoose condition API listed ConditionExpression, so I thought I was using the DynamoDB API incorrectly. That maybe a bug?

Doubtful. You can use the Dynamoose Condition class for both FilterExpression or ConditionExpression. It depends on what you pass into it. As an example, doing `Model.scan` uses FilterExpression, whereas `Model.update` uses ConditionExpression.

So internally `requestObject` takes in a settings object. One of the properties on this object is `conditionString`. By default that is set to ConditionExpression.

https://github.com/dynamoose/dynamoose/blob/ed6f3802f7281dbd85987ac58b0661c2fc686417/lib/Condition.ts#L232

However, for things like Scan, we set it to FilterExpression.

https://github.com/dynamoose/dynamoose/blob/ed6f3802f7281dbd85987ac58b0661c2fc686417/lib/DocumentRetriever.ts#L149

> Dynamoose throws an error here, as it's expecting FilterExpression to be an array

Need a stack trace here to even begin to guess at what is going on. I'm assuming the MCVE to reproduce this is the following?

```js
const condition = new dynamoose.Condition({
    FilterExpression: '#createdAtCol <= :createdAtValue OR #updatedAtCol <= :updatedAtValue',
    ExpressionAttributeValues: {
        ':createdAtValue': {
            N: String(now - DELETION_THRESHOLD_MS)
        },
        ':updatedAtValue': {
            N: String(now - DELETION_THRESHOLD_MS)
        },
    },
    ExpressionAttributeNames: {
        '#createdAtCol': 'createdAt',
        '#updatedAtCol': 'updatedAt',
    },
});
const results = await Model.scan(condition).exec();
```

And it fails on results?

If that looks correct for the MCVE, please provide a full stack trace so I can look into this more. I know when I was debugging the original problem that I did a test almost identical to this and it worked as expected for me. So I'm not sure what is going on here.

> I cannot remember the exact issues I was facing then, unfortunately.

Got it. If you ever happen to remember, please submit an issue. That goes for future things as well. Really want to get problems users are having resolved.

**Comment by dipack95** [comment]
@fishcharlie The MCVE script is as follows:

```javascript
const dynamoose = require('dynamoose');

const ddb = new dynamoose.aws.sdk.DynamoDB({
  region: 'eu-west-1',
  version: 'latest',
});

dynamoose.aws.ddb.set(ddb);
const tableName = 'dipack_dynamoose_bug_repro';
const definition = new dynamoose.Schema(
  {
    id: {
      type: String,
      required: true,
    },
    value: {
      type: String,
      required: true,
    },
    randomNumber: {
      type: Number,
      required: true,
    },
  },
  {
    /**
     * Let Dynamoose manage the `createdAt` and `updatedAt` timestamps,
     * Unix epoch in seconds (not milliseconds)
     */
    timestamps: true,
  },
);
const DELETION_THRESHOLD_MS = (1000 * 60);
const now = Date.now();
const condition = new dynamoose.Condition({
  FilterExpression: '#createdAtCol <= :createdAtValue',
  ExpressionAttributeValues: {
    ':createdAtValue': {
      N: String(now - DELETION_THRESHOLD_MS)
    },
  },
  ExpressionAttributeNames: {
    '#createdAtCol': 'createdAt',
  },
});
(async () => {
  const Model = dynamoose.model(tableName, definition, { create: true });
  const results = await Model.scan(condition).exec();
})();
```

And the stack trace is:
```bash
(node:47333) UnhandledPromiseRejectionWarning: TypeError: expression.reduce is not a function
    at Object.convertConditionArrayRequestObjectToString (/Users/dipack/projects/dynamoose-bug-repro-fix/.yarn/cache/dynamoose-https-203b70f741-c93a228dee.zip/node_modules/dynamoose/lib/utils/dynamoose/convertConditionArrayRequestObjectToString.ts:2:20)
    at Scan.DocumentRetriever.getRequest (/Users/dipack/projects/dynamoose-bug-repro-fix/.yarn/cache/dynamoose-https-203b70f741-c93a228dee.zip/node_modules/dynamoose/lib/DocumentRetriever.ts:251:45)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at /Users/dipack/projects/dynamoose-bug-repro-fix/.yarn/cache/dynamoose-https-203b70f741-c93a228dee.zip/node_modules/dynamoose/lib/DocumentRetriever.ts:114:20
    at /Users/dipack/projects/dynamoose-bug-repro-fix/break.js:48:19
(Use `node --trace-warnings ...` to show where the warning was created)
(node:47333) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:47333) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

> So internally requestObject takes in a settings object. One of the properties on this object is conditionString. By default that is set to ConditionExpression.

Ah, thank you for clearing that up! That makes sense! I guess using undocumented APIs has its own perils :)

**Comment by fishcharlie** [comment]
@dipack95 I found this bug right after I posted that message. Just pushed a new commit to that same PR/branch. Mind testing it now and let me know if it works for you.

**Really** appreciate you finding 2 bugs and helping me to fix them.

For Queries (not Scans) I'm still working on tracking down a different issue and will hopefully push a new commit for that issue soon.

**Comment by dipack95** [comment]
@fishcharlie Ha, that's awesome! Thank you once again for being so responsive, and helpful. :)

I don't see the commit (yet) on #1324 that fixes the second bug, but I believe you when you say you've fixed it! Let me know if you need any help testing it!

**Comment by fishcharlie** [comment]
@dipack95 Forgot to push 😆. Check again now.

**Comment by dipack95** [comment]
@fishcharlie It worked! 🥳
